name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        # sama as npm ci
        run: yarn install --frozen-lockfile

      - run: npm run build
        env:
          TURBO_TOKEN: lLlMav0KI8zoYT9bFVZkYlMQ
          TURBO_TEAM: cognu-co

      - name: Deploy Storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
